version: "3.0"

services:
    borgserver:
        container_name: borgserver
        image: valmati/borgserver
        environment:
            - UID=1000
            - GID=1000
        ports:
            - "2222:22"
        volumes:
            - ./host_keys:/etc/ssh/host_keys/
            - ./authorized_keys:/etc/authorized_keys/
            - ./backups:/backups
