version: "3.0"

services:
    borgserver:
        container_name: borgserver
        image: valmati/borgserver
        hostname: borgserver
        environment:
            - UID=1000
            - GID=1000
            - TZ=Europe/Madrid
            - RESTRICT_TO_PATH=true
        ports:
            - "2222:22"
        volumes:
            - ./host_keys:/etc/ssh/host_keys/
            - ./authorized_keys:/etc/authorized_keys/:ro
            - ./backups:/backups
        restart: unless-stopped
